[build-system]
requires = [
    "setuptools",
    "tomli ~= 2.0.1; python_version < '3.11'",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py37']

[tool.mypy]
exclude = [
    "build",
    "venv"
]
